### ISSUE TITLE
no man sky connect stuck on offline mode "Server is temporarily unavailable"

### ISSUE THREAD

**Issue by zangetssuu** [jaszhix/NoMansConnect#116]
Unless this is a feature request, ALL of the following is required:

- Description of the problem
- Windows version
- NMC version
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
- settings.json

- How can this bug be reproduced?

**Comment by zangetssuu** [comment]
i have an issue every time starting the game and app i am in the offline mode 

latest update from steam for no man sky 

username/AppData\Roaming\HelloGames\NMS

for both save files and install directory 
running windows 10 build 1903

need help please

**Comment by jaszhix** [comment]
Have you tried switching back to online mode? Do that by clicking the wrench icon in the upper right, click Settings, and click "Offline mode".

I've been using the experimental branch of No Man's Sky, and haven't been seeing issues with compatibility since Beyond released. The server might be overloaded at the moment, which might be helped by the [version I just released, 1.5.10](https://github.com/jaszhix/NoMansConnect/releases/tag/v1.5.10).

**Comment by zangetssuu** [comment]
Yes kept restarting and having the same issue says on the top no man sky disconnect pissed me off so I switched my pc off for the day 💀

**Comment by jaszhix** [comment]
Check your firewall and antivirus software - they sometimes will silently block the app because it's obscure and not well known. If that happens, the app reverts to offline mode.
