### ISSUE TITLE
[Request] To adjust/change Galaxy Name

### ISSUE THREAD

**Issue by BloodedRogue** [jaszhix/NoMansConnect#133]
I was hoping that there could be a feature to change the galaxy name in NoMansConnect.

For example, I adjusted my RealityIndex in json  to and I used the Save/Warp feature to ensure I was in my ship (worked as intended), however the galaxy that is logged in No Mans Sky is different from what's logged into NoMansConnect.

So I'm requesting that we be able to adjust or rename the galaxy as seen in the game. :)

**Comment by jaszhix** [comment]
I don't recommend changing the RealityIndex manually because the old positional data from the previous galaxy might leave you stranded in space, or clipped under terrain. 

The locations themselves are uniquely identified by their galaxy address and RealityIndex, so if you are changing NMC JSON data manually (settings.json), that is not supported. If you change your save file manually, NMC should log it as a new location. If you just want to change only the galaxy, you can copy the Galactic Address, and register a new location manually - teleporting to manually registered locations will spawn you in your ship in space.
