### ISSUE TITLE
First time using, and locked out.

### ISSUE THREAD

**Issue by FL8KT** [jaszhix/NoMansConnect#167]
Unless this is a feature request, ALL of the following is required:

- Description of the problem
I have never used NMC before and it says my username is protected and I need to send a recovery email.
- Windows version
Windows 10 Home
- NMC version
2.52
- Absolute path to your storage_x.hg files.
C:\Users\jacob\AppData\Roaming\HelloGames\NMS\st_76561198142781105
- Absolute path to your NMS install directory.
D:\Steam\steamapps\common\No Man's Sky
Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/4863272/NMC.log)

[settings.json.txt](https://github.com/jaszhix/NoMansConnect/files/4863277/settings.json.txt)

- NMC.log
- settings.json

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced?
I don't know.

**Comment by jaszhix** [comment]
I'm guessing it's username collision because steam lets you change it, so someone might have already registered locations with the same username. NMS caches the steam username in the save file, which is where the app gets it from. You could see if changing your username in the menu works. If not, I can look at a fix so that works for users that are locked out.
