### ISSUE TITLE
Ignoring Windows "SetWindowsPos" calls

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#4]
Hi, I use applications to control windows positions and it seems that this app is ignoring these calls by windows for position.

**Comment by jaszhix** [comment]
Yes, this happens because NMC uses window transparency for overlay mode. I'm not sure if this is specific to Electron or a Win32 issue, but removing transparency while in overlay mode would be the only way to fix it. There's actually another bug that nobody knows about because its being overrided by this limitation with the window, but NMC has the ability to save its own window position. I will consider removing transparency.
