### ISSUE TITLE
NMConnect online ?

### ISSUE THREAD

**Issue by mhebrard** [jaszhix/NoMansConnect#66]
Hello, 
More a suggestion that an issue.
It would be nice to access NMConnect database online.
Let say I encourage the members of my favorite Space Civilization to enter their locations in NMConnect, and I wish to display a map on the website of my favorite Civilization.

Is t possible to add that kind of API or web access to the DB ?

**Comment by jaszhix** [comment]
If you are curious, you can experiment with the API by cloning the repo and working in chrome devtools. Its not something I'd like to encourage due to CPU overhead on the server, though. So not likely to be something I officially support, but you're welcome to experiment with it as long the server resources aren't being overused.

**Comment by mhebrard** [comment]
OK, I might take a look, and be careful to not overused the server... letting you know
