### ISSUE TITLE
NoMansConnect.Setup.1.3.1.exe is detected as a virus

### ISSUE THREAD

**Issue by JJEU** [jaszhix/NoMansConnect#85]
Hello,

I just downloaded the 1.3.1 version (uploaded 8 minutes ago ! )

1 -  i am on windows 10, when i launch the .exe, smarscreen prevents me to do so. i have to click a link then click "i understand the risk"

2 - I uploded the file on virustotal.com
most antivirus don't detect this as a virus, except two of them. Comodo thinks it's a trojan

You may contact them and provide the source code if needed.

**Comment by jaszhix** [comment]
Hi, there is nothing I can do about this unfortunately. For Windows Defender smart screen, it is doing this because it is an unsigned file of relative obscurity (signing costs $$$/year). The other two AV results are always positive for all my releases and they are false positives. 

[2/65](https://www.virustotal.com/en/file/9f9d0f88bbe585cf451273035975f24c24316a0e34c0984c4952bab348165a04/analysis/) is an acceptable margin of error.
