### ISSUE TITLE
Version Compatibility resets on cache reset for manually registered locations

### ISSUE THREAD

**Issue by Randshot** [jaszhix/NoMansConnect#88]
I have noticed that, when I reset my remote cache, the version compatibility setting also resets (to x) for manually added locations.

You can reproduce it by doing the following:
- Manually register a location
- Mark it is compatible
- (Optional: Sync locations -> does not seem to help)
- Reset remote cache
It should now be marked as 'incompatible'.

**Comment by Randshot** [comment]
@jaszhix I think I found the cause.
The stored locations drop down just updated and showed that the location I manually added was already explored by someone before in a previous version of NMS.
(*For reference, the system I am talking about is: **042F:0078:0D55:0021***)

**Comment by jaszhix** [comment]
I'm able to reproduce the location updating problem on those. This is happening because the stored location list doesn't get updated by the corresponding server location. If you copy the "Universe Address" to the clipboard, search, press Enter, it will show up in the results as compatible with your current version. This could be grouped with #90.

**Comment by Randshot** [comment]
I can't find my old entry anymore, so I can't confirm this.
Feel free to close this issue, if you think you have resolved it.

**Comment by jaszhix** [comment]
I just renamed it on the server so the version it synchronizes with is up-to-date.
