### ISSUE TITLE
Unable to find reference remote location from stored locations cache

### ISSUE THREAD

**Issue by djehmli** [jaszhix/NoMansConnect#89]
First of all the 'Old Man's Connect' you have added as a header when a new release is available?  Priceless, ingenious and caused me to crack up when I opened the app a few moments ago.

Secondly, perusing the NMS.log I am finding a few of these

1533509881674:    "Finished reading No Man's Sky v4626 save file." 
1533509896492:    "SAVE DIRECTORY: " "C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS" 
1533509896564:    "USERNAME: " "djehmli" 
1533509896638:    "Finished reading No Man's Sky v4626 save file." 
1533509906420:    "Unable to find reference remote location from stored locations cache

The above is then followed with what appears to be every single location and flora, fauna and mineral detail I've ever captured.   The file log file itself exploded in size.

What I've discovered is this appears to happen on planets where I save an alien base location.  How I potentially found this is the the one system where I am performing the Awakening quest which has you going from alien residence to alien residence is about where the messages start to show in the log file.  Also in the stored locations drop down, the planet in question does not display the detail box when you left click on it.  I finally figured out the display delay is the log file exploding.

If I do nothing but land on the planet, jump out, scan a few flora and fauna, jump in and then jump out of ship to save - no log file explosion.  

But if I land at an alien facility, scan and save at their way point, kaboom.

**Comment by jaszhix** [comment]
Thanks for the nice comments. 

Those warnings are not connected to the discoveries in the profile. When you select an item in the stored location list, the app cross-references it with the remote location so it can get the most up to date metadata for it (favorites, teleports, etc). This means it won't be updated but should still display it. But usually if this is happening to new locations, it means it hasn't had a chance to grab the version from the server yet - which happens based on the polling rate frequency. What should be happening is we get that specific version back once its uploaded to the API, and I probably didn't because the AJAX code got complicated by adding worker threads.

Though its hard to get a complete picture without the whole log, it generally can be ignored and is there to help me to eventually improve the way locations are handled.

**Comment by jaszhix** [comment]
Uploaded a [pre-release version](https://github.com/jaszhix/NoMansConnect/releases/tag/v1.3.3-rc) you can test that should fix this.

**Comment by djehmli** [comment]
Grabbed pre-release and played a couple of hours off and on, happy to report a clean log file.  No display lag or issues editing or working through/ sorting records.
